const styles = (theme) => ({
  Container: {
    background: 
        "linear-gradient(147deg, #0E8EB1 0%, #A1D2D5 68%, #E6E6E6 100%), #088CBA",
    fontFamily: 'Lato, "Open Sans", sans-serif',
    padding: "0px 16px 80px",
    boxShadow: "0px 4px 20px 0px #00000040 inset",
    [theme.breakpoints.up("md")]: {
      padding: "0px 32px 120px",
    },
    "@media (min-width: 1400px)": {
      padding: "0px 92px 120px",
    },
  },

  // Hero Section Styles
  HeroSection: {
    padding: "30px 32px 55px",
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    overflow: "hidden",
    margin: "auto",
  },
  HeroIconWrapper: {
    position: "relative",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: "20px",
    width: "103px",
    height: "103px",
    margin: "0 auto 20px",
  },
  LockBorder: {
    position: "absolute",
    width: "103px",
    height: "103px",
    top: 0,
    left: 0,
  },
  HeroIcon: {
    position: "relative",
    width: "101px",
    height: "101px",
    zIndex: 1,
  },
  HeroTitle: {
    fontFamily: "Inter",
    fontSize: "30px",
    fontWeight: 500,
    color: "#004D73",
    marginTop: "10px",
    lineHeight: "107%",
    letterSpacing: "-2%",
  },

  // Content Wrapper
  ContentWrapper: {
    margin: "auto",
    padding: "0px",
  },
  ColumnContainer: {
    gap: "60px",
    justifyContent: "center",
    [theme.breakpoints.down("sm")]: {
      gap: "40px",
    },
  },

  // Combined Login Box Styles
  CombinedLoginBox: {
    backgroundColor: "#F0F8FA",
    borderRadius: "35px",
    padding: "30px 40px 50px",
    marginBottom: "40px",
    boxShadow: "0px 2px 10px 0px #00000040",
    border: "3px solid #F4FBFE",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "40px",
  },
  RightColumn: {
    [theme.breakpoints.up("md")]: {
      maxWidth: "329px",
    },
    // marginLeft: "60px",
  },
  LeftColumn: {
    [theme.breakpoints.up("md")]: {
      maxWidth: "876px",
    },
  },
  LoginSection: {
    alignSelf: "stretch",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "25px",
  },
  RasSection: {
    alignSelf: "stretch",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  RasTextWrapper: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "25px",
    minWidth: 0,
  },
  VerificationWrapper: {
    width: "100%",
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    gap: "100px",
  },
  VerificationSection: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "10px",
    "& $BodyText": {
      paddingRight: "50px",
    },
  },
  VerificationHeader: {
    alignSelf: "stretch",
    paddingRight: "10px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    cursor: "pointer",
  },
  VerificationTitle: {
    flex: 1,
    fontFamily: "Inter",
    fontSize: "20px",
    fontWeight: 600,
    color: "#000",
    lineHeight: "26px",
  },
  VerificationText: {
    width: "100%",
    fontFamily: "Roboto",
    fontSize: "16px",
    fontWeight: 400,
    color: "#000",
    lineHeight: "150%",
    paddingRight: "50px",
  },
  Divider: {
    alignSelf: "stretch",
    width: "100%",
    height: "0px",
    borderTop: "1px solid #8A8A8A",
    margin: "25px 0",
  },
  orderedListAlpha: {
    margin: "2px 0px 30px 0px",
    paddingLeft: "48px",

    fontFamily: "Roboto",
    fontWeight: 400,
    fontSize: "16px",
    color: "#000",
    letterSpacing: "0.2px",
    lineHeight: "150%",
    "& li": {
      marginBottom: "2px",
      paddingLeft: "4px",
    },
  },
  orderedListNumeric: {
    margin: "2px 0",
    paddingLeft: "25px",
    fontFamily: "Roboto",
    fontSize: "16px",
    color: "#000",
    letterSpacing: "0.2px",
    lineHeight: "150%",
    "& li": {
      marginBottom: "2px",
      paddingLeft: "4px",
    },
  },
  unorderedList: {
    margin: "2px 0",
    paddingLeft: "25px",
    fontFamily: "Roboto",
    fontSize: "16px",
    color: "#000",
    letterSpacing: "0.2px",
    lineHeight: "150%",
    "& li": {
      marginBottom: "2px",
      paddingLeft: "4px",
    },
  },
  nestedList: {
    margin: "2px 0",
    paddingLeft: "20px",
    listStyleType: "disc",
    "& li": {
      marginBottom: "2px",
      paddingLeft: "4px",
    },
  },
  LoginContentRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "20px",
    paddingTop: "20px",
  },
  LoginTextContent: {
    width: "537px",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "17px",
  },
  LoginButtonContainer: {
    display: "flex",
    alignItems: "flex-start",
  },
  BoxTitle: {
    height: "37px",
    fontFamily: "Inter",
    fontSize: "24px",
    fontWeight: 700,
    color: "#18588E",
    letterSpacing: "-0.02em",
    lineHeight: "106.52%",
    display: "flex",
  },
  BodyText: {
    fontFamily: "Roboto",
    fontSize: "16px",
    fontWeight: 400,
    color: "#000",
    letterSpacing: "0.2px",
    lineHeight: "150%",
    marginBottom: "0px",
  },
  NoteText: {
    fontFamily: "Roboto",
    fontSize: "16px",
    fontWeight: 700,
    color: "#000",
    letterSpacing: "0.2px",
    lineHeight: "150%",
  },
  FooterNote: {
    fontFamily: "Roboto",
    fontSize: "16px",
    fontWeight: 400,
    color: "#000",
    letterSpacing: "0.2px",
    lineHeight: "150%",
  },
  LoginButtonEra: {
    width: "213px",
    height: "47px",
    fontFamily: "Roboto",
    fontSize: "16px",
    fontWeight: 500,
    color: "#000000",
    backgroundColor: "#FFFFFF",
    border: "1.25px solid #3795A9",
    borderRadius: "10px",
    padding: "11px 14px",
    gap: "10px",
    textTransform: "none",
    textAlign: "center",
    lineHeight: "24.5px",
    whiteSpace: "nowrap",
    "&:hover": {
      backgroundColor: "#F0F9F7",
      border: "1.25px solid #3795A9",
    },
  },
  LoginButtonRas: {
    width: "215px",
    height: "47px",
    fontFamily: "Roboto",
    fontSize: "16px",
    fontWeight: 500,
    color: "#000000",
    backgroundColor: "#FFFFFF",
    border: "1.25px solid #3795A9",
    borderRadius: "10px",
    padding: "11px 53px",
    gap: "10px",
    textTransform: "none",
    lineHeight: "24.5px",
    whiteSpace: "nowrap",

    letterSpacing: "0%",

    "&:hover": {
      backgroundColor: "#F0F9F7",
      border: "1.25px solid #3795A9",
    },
  },

  // Help Sidebar Styles
  HelpSidebar: {
    backgroundColor: "#004D73",
    borderRadius: "35px",
    padding: "20px 30px 50px 30px",
    color: "#FFFFFF",
    boxShadow: "0px 2px 10px 0px #00000040",
  },
  HelpHeader: {
    display: "flex",
    alignItems: "center",
    marginBottom: "15px",
    gap: "15px",
  },
  HelpIcon: {
    width: "52px",
    height: "52px",
  },
  HelpHeaderText: {
    fontFamily: "Nunito",
    fontSize: "18px",
    fontWeight: 600,
    color: "#FFFFFF",
    lineHeight: "107%",
    letterSpacing: "5%",
    textTransform: "uppercase",
  },
  TutorialSection: {
    marginBottom: "60px",
    padding: "0px 10px",
  },
  SidebarTitle: {
    fontFamily: "Inter",
    fontSize: "24px",
    fontWeight: 700,
    color: "#8BEAFB",
    marginBottom: "5px",
    lineHeight: "112%",
    letterSpacing: "-2%",
  },
  SidebarText: {
    fontFamily: "Lato",
    fontSize: "16px",
    fontWeight: 400,
    color: "white",
    lineHeight: "21px",
    letterSpacing: "0.2px",
  },
  VideoThumbnail: {
    marginTop: "25px",
    cursor: "pointer",
    position: "relative",
    overflow: "hidden",
  },
  VideoImage: {
    width: "100%",
    height: "auto",
    display: "block",
  },
  PlayOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "8px",
  },
  PlayIcon: {
    width: "23%",
    height: "auto",
  },
  ContactSection: {
    marginTop: "40px",
    padding: "0px 10px",
  },
  ContactButton: {
    fontFamily: "Roboto",
    fontSize: "16px",
    fontWeight: 500,
    color: "#000",
    backgroundColor: "#FFF",
    border: "1.25px solid #3795A9",
    borderRadius: "10px",
    padding: "11px 53px",
    textTransform: "none",
    width: "100%",
    lineHeight: "24.5px",
    "&:hover": {
      backgroundColor: "rgba(255, 255, 255, 0.9)",
      border: "1.25px solid #3795A9",
    },
    maxWidth: "213px",
    height: "47px",
    display: "block",
    margin: "26px auto 0",

  },

  // Request Access Section
  RequestSection: {
    padding: "30px 40px 40px 40px",
    marginTop: "40px",
    backgroundColor: "#F0F8FA",
    borderRadius: "35px",
    boxShadow: "0px 2px 10px 0px #00000040",
    border: "3px #F4FBFE solid",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  RequestTopSection: {
    alignSelf: "stretch",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "15px",
  },
  RequestBottomSection: {
    alignSelf: "stretch",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "15px",
  },
  SectionTitle: {
    height: "37px",
    fontFamily: "Inter",
    fontSize: "24px",
    fontWeight: 700,
    color: "#18588E",
    lineHeight: "25.57px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  SubsectionTitle: {
    fontFamily: "Inter",
    fontSize: "20px",
    fontWeight: 600,
    color: "black",
    marginTop: "17px",
    marginBottom: "17px",
    lineHeight: "130%",
    letterSpacing: "0%",
  },
  DocumentationList: {
    fontFamily: "Roboto",
    fontSize: "16px",
    listStyleType: "none",
    paddingLeft: "0px",
    "& li": {
      marginBottom: "4px",
    },
  },
  Link: {
    color: "#990099",
    textDecoration: "underline",
    fontWeight: 400,
    cursor: "pointer",
    letterSpacing: "0.2px",
    lineHeight: "150%",
    "&:hover": {
      textDecoration: "underline",
    },
    fontFamily: "Roboto",
    fontSize: "16px",
    "& $unorderedList": {
      color: "#990099",
    },
  },

  // Warning Section
  WarningSection: {
    width: "100%",
    padding: "30px 40px",
    marginTop: "40px",
    backgroundColor: "#F4FBFE",
    borderRadius: "35px",
    boxShadow: "0px 2px 10px 0px #00000040",
    border: "3px #BA1F40 solid",
    display: "flex",
    gap: "40px",
  },
  WarningContent: {
    flex: "1 1 0",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "15px",
  },
  WarningToggle: {
    paddingRight: "10px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    cursor: "pointer",
  },
  WarningTitle: {
    fontFamily: "Inter",
    fontSize: "20px",
    fontWeight: 600,
    color: "#BA1F40",
    lineHeight: "130%",
    letterSpacing: "0%",
  },
  WarningText: {
    flex: 1,
    fontFamily: "Roboto",
    fontSize: "16px",
    fontWeight: 400,
    color: "black",
    lineHeight: "24px",
    letterSpacing: "0.2px",
    paddingRight: "30px",
  },
  WarningTextCollapsed: {
    overflow: "hidden",
    display: "-webkit-box",
    WebkitLineClamp: 1,
    WebkitBoxOrient: "vertical",
    textOverflow: "ellipsis",
    marginRight: "10px",
    wordSpacing: "3px",
  },
});

export default styles;
