export default () => ({
  container: {
    position: 'relative',
    width: '100%',
    margin: '35px auto 0 auto',
    paddingLeft: '85px',
    paddingRight: '85px',
  },
  paragraph: {
    position: 'absolute',
    fontFamily: 'Nunito',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: '16px',
    letterSpacing: '0.2px',
    color: '#000000',
  },
  paginatedTableWrapper: {
    overflowY: 'auto',
    marginBottom: '100px',
  },
  tableButtonRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    paddingTop: '12px',
    paddingBottom: '28px',
  },
  cartButton: {
    backgroundColor: '#06846A',
    color: '#FFFFFF',
    fontFamily: 'Roboto',
    fontWeight: 500,
    fontSize: '14px',
    lineHeight: '14px',
    letterSpacing: '0px',
    textAlign: 'center',
    textTransform: 'uppercase',
    padding: '16px 20px',
    width: '177px',
    height: '46px',
    borderRadius: '10px',
    '&:hover': {
      backgroundColor: '#046D57',
    },
    '&.Mui-disabled': {
      backgroundColor: '#06846A',
      color: '#FFFFFF',
      opacity: 0.5,
    },
  },
  tooltipIconButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    display: 'inline-flex',
    alignItems: 'center',
    '&:focus': {
      outline: '2px solid #005EA2',
      outlineOffset: '2px',
    },
  },
  questionMarkIcon: {
    color: '#000000',
    width: '10px',
    height: '10px',
    verticalAlign: 'top',
    cursor: 'pointer',
    marginLeft: '4px',
  },
  tooltipBody: {
    backgroundColor: '#FFFFFF',
    color: '#223D4C',
    fontSize: '13px',
    fontWeight: '600',
    fontFamily: 'Lato, sans-serif',
    lineHeight: '19px',
    width: '244px',
    minHeight: '75px',
    paddingTop: '10px',
    paddingRight: '15px',
    paddingBottom: '10px',
    paddingLeft: '15px',
    borderRadius: '5px',
    border: '1px solid #C3C3C3',
    opacity: 1,
    gap: '10px',
    boxShadow: '0px 4px 10px 0px #00000040',
  },
});
